theme: jekyll-theme-minimal
title: Peishi Liu - Personal Website
description: Welcome to Peishi Liu's personal website! Robotics Engineer & Mechatronics Master Student

# Personal information
author: Peishi Liu
email: your.email@example.com
location: Munich, Germany

# Social links
github_username: from1tomax
linkedin_username: peishi-liu

# Website settings
show_downloads: false
google_analytics: # Add your Google Analytics ID here if needed

# SEO settings
lang: en-US
plugins:
  - jekyll-seo-tag
